//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.239
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileMonkey {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class language : global::System.Configuration.ApplicationSettingsBase {
        
        private static language defaultInstance = ((language)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new language())));
        
        public static language Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Estado del Sonar:")]
        public string lblEstadoES {
            get {
                return ((string)(this["lblEstadoES"]));
            }
            set {
                this["lblEstadoES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sonar State:")]
        public string lblEstadoEN {
            get {
                return ((string)(this["lblEstadoEN"]));
            }
            set {
                this["lblEstadoEN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Activo")]
        public string lblEstadoActivoES {
            get {
                return ((string)(this["lblEstadoActivoES"]));
            }
            set {
                this["lblEstadoActivoES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Active")]
        public string lblEstadoActivoEN {
            get {
                return ((string)(this["lblEstadoActivoEN"]));
            }
            set {
                this["lblEstadoActivoEN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Inactivo")]
        public string lblEstadoInactivoES {
            get {
                return ((string)(this["lblEstadoInactivoES"]));
            }
            set {
                this["lblEstadoInactivoES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Inactive")]
        public string lblEstadoInactivoEN {
            get {
                return ((string)(this["lblEstadoInactivoEN"]));
            }
            set {
                this["lblEstadoInactivoEN"] = value;
            }
        }
    }
}
